### ISSUE TITLE
rotating_svg error 

### ISSUE THREAD

**Issue by paulrichards999** [trevordevore/livecode-extensions#1]
Hi Trevor, 
I am trying to use your fantastic rotating_svg widget (the answer to all my prayers!!!) but when I try installing/testing the widget through extension builder, it fails to compile with various "illegal token" messages.  The helpers have been also been installed.  Using Windows 10 and LC 8.1.6 rc2 

9:34 AM: Compiling module C:/LIVECODE/Livecode WIDGETS/Rotating SVG/rotatingSVG.lcb
9:34 AM: Error: on line 1 (): 
9:34 AM: Error: on line 1 (): 
9:34 AM: Error: on line 1 (): 
9:34 AM: Error: C:/LIVECODE/Livecode WIDGETS/Rotating SVG/rotatingSVG.lcb:1:1: error: Illegal token 'ï'
C:/LIVECODE/Livecode WIDGETS/Rotating SVG/rotatingSVG.lcb:1:2: error: Illegal token '»'
C:/LIVECODE/Livecode WIDGETS/Rotating SVG/rotatingSVG.lcb:1:3: error: Illegal token '¿'

9:34 AM: Error: failed to compile module
9:34 AM: Error: no id found in  C:/LIVECODE/Livecode WIDGETS/Rotating SVG/rotatingSVG.lcb

Widgets are currently beyond me at the moment, so any help would be graciously received :-)

**Comment by trevordevore** [comment]
@paulrichards999 I tried compiling rotatingSVG.lcb in 8.1.6 rc-3 on OS X and received one error. 8.1.6 doesn't like `returns nothing` in function definitions. I've removed that and the widget compiles for me now. The change is on GitHub.

Your error looks different than what i received though. It appears to me that you are trying to compile some sort of binary file. The illegal tokens mentioned don't appear anywhere in the rotatingSVG.lcb file.  Can you verify that the source file on your computer looks like the one on Github? https://github.com/trevordevore/livecode-extensions/blob/master/rotating_svg/rotatingSVG.lcb

**Comment by paulrichards999** [comment]
@trevordevore Thank you sooooo much!!   I copied the text again from raw, and overwrote what was in existing file (using Notepad this time) and the Widget has compiled and installed. 

I cannot thank you enough, 1 for this fantastic widget, and 2, for helping so quickly.

**Comment by trevordevore** [comment]
You're welcome @paulrichards999
