### ISSUE TITLE
Unable to install some widgets in LiveCode Indy 9.6.1

### ISSUE THREAD

**Issue by Monox18** [trevordevore/livecode-extensions#2]
Hello Trevor,

Thank you for such amazing widgets. I arrived here trying to find a better slider than the LC's built in which doesn't have a proper look and feel in mobile. I found yours. It looks great and behaves just as expected. Works the same in Android which makes it perfect. 

So I wanted to test out the other widgets and I have a problem. I try to install the widget_helpers module and apparently it installs properly. But when installing the breadcrumb_nav it throws an error. Any ideas?

![Screenshot 2021-01-12 00 37 51](https://user-images.githubusercontent.com/10236768/104252473-72905a80-5472-11eb-86ff-bb120131c576.png)
![Screenshot 2021-01-12 00 58 43](https://user-images.githubusercontent.com/10236768/104252474-73c18780-5472-11eb-9dae-79a561d9d105.png)

**Comment by Monox18** [comment]
Oh nevermind. It seems my IDE was glitched. I had to unistall them all and reset my PC to make it work. I can confirm all widgets are working up to this date. Awesome. Thanks for making them available to the community!

**Comment by trevordevore** [comment]
You're welcome @Monox18. I'm glad you got the widgets working.
